"""Pydantic models for narrative analysis protocols.

These models define the configuration, roles, and outputs for the
seven analysis protocols (P1–P7) from the protocol framework.
"""

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, Field

from narratological.models.analyst import AnalystRole


class ProtocolLevel(StrEnum):
    """Available protocol levels."""

    P1 = "P1"
    P2 = "P2"
    P3 = "P3"
    P4 = "P4"
    P5 = "P5"
    P6 = "P6"
    P7 = "P7"


class ProtocolSpec(BaseModel):
    """Specification of an analysis protocol.

    Defines the roles activated, documents generated, and estimated time
    for a given protocol level.
    """

    level: ProtocolLevel = Field(description="Protocol level (P1-P7)")
    name: str = Field(description="Name of the protocol")
    purpose: str = Field(description="Primary analytical purpose")
    roles: list[AnalystRole] = Field(
        default_factory=list,
        description="Analyst roles activated by this protocol",
    )
    documents: list[str] = Field(
        default_factory=list,
        description="Documents generated by this protocol",
    )
    time_estimate: str = Field(description="Typical time estimate for analysis")
